# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9c316b767ae1e0aaeb656128a84b10d283b301f8df1fc8d155cbef3146719fa0e07de0d8565ea9c462e98f5be7545e756442e29970c25846aea028c8fb244d5f

test:
  secret_key_base: 82d9d84ba3b1f48ae74b79d36134c2d667ef3084f308ef03ae4cb98fb5280eda6593c29802b3cf8669e00626eb16273a24fbf4df9e2b617c926d85d6566e6226

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
